oc_platform_homepage:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Annonce:index
        page:        1
    requirements:
        page: \d*

oc_platform_view:
    path:      /annonce/{id}
    defaults:
        _controller: OCPlatformBundle:Annonce:view
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Annonce:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Annonce:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Annonce:delete
    requirements:
        id: \d+