oc_platform_homepage:
    path:     /platform
    defaults: { _controller: OCPlatformBundle:Annonce:index }

oc_platform_home:
    path:      /platform
    defaults: { _controller: OCPlatformBundle:Annonce:index }

oc_platform_view:
    path:      /platform/advert/{id}
    defaults: { _controller: OCPlatformBundle:Annonce:view }

oc_platform_add:
    path:      /platform/add
    defaults: { _controller: OCPlatformBundle:Annonce:add }